language: php

sudo: false

addons:
  apt:
    packages:
      - tidy

before_install:
  - pip install --user codecov

env:
  global:
    - MODULE_PATH=framework
    - COVERAGE_TESTS=0
    - CORE_RELEASE=master
    - "ARTIFACTS_AWS_REGION=us-east-1"
    - "ARTIFACTS_S3_BUCKET=silverstripe-travis-artifacts"
    - secure: "DjwZKhY/c0wXppGmd8oEMiTV0ayfOXiCmi9Lg1aXoSXNnj+sjLmhYwhUWjehjR6IX0MRtzJG6v7V5Y+4nSGe+i+XIrBQnhPQ95Jrkm1gKofX2mznWTl9npQElNS1DXi58NLPbiB3qxHWGFBRAWmRQrsAouyZabkPnChnSa9ldOg="
    - secure: "UmbXCNLK0f2Dk+7qX8bOVcgIt4QhRvccoWvMUxaPtIU+95HCbG10eeCxvfOeBax+tHcRXmeCG4vM4tcuT/WoANkAma/VX74DylFjbWhks2tsKOcr2kjTrOwe6Q9CXOBjVAlcx0lnV/a+w83KARjXGnCrIbE7p7r4EDw31rkVufg="

matrix:
  include:
    # Run coverage tests in parallel - each number is a different suite of tests
    - php: 5.6
      env: DB=MYSQL COVERAGE_TESTS=1
    - php: 5.6
      env: DB=MYSQL COVERAGE_TESTS=2
    - php: 5.6
      env: DB=MYSQL COVERAGE_TESTS=3
    - php: 5.6
      env: DB=MYSQL COVERAGE_TESTS=4
    - php: 5.6
      env: DB=MYSQL COVERAGE_TESTS=5
    - php: 5.6
      env: DB=MYSQL COVERAGE_TESTS=6
    - php: 5.6
      env: DB=MYSQL COVERAGE_TESTS=7
    - php: 5.6
      env: DB=MYSQL COVERAGE_TESTS=8
    - php: 5.6
      env: DB=MYSQL COVERAGE_TESTS=9
    - php: 5.6
      env: DB=MYSQL COVERAGE_TESTS=10
    - php: 5.6
      env: DB=MYSQL COVERAGE_TESTS=11
    - php: 5.6
      env: DB=MYSQL COVERAGE_TESTS=12
    - php: 5.6
      env: DB=MYSQL COVERAGE_TESTS=13
    - php: 5.6
      env: DB=MYSQL COVERAGE_TESTS=14
    - php: 5.6
      env: DB=MYSQL COVERAGE_TESTS=15
    - php: 5.6
      env: DB=MYSQL COVERAGE_TESTS=16
    - php: 5.6
      env: DB=MYSQL COVERAGE_TESTS=17
    - php: 5.6
      env: DB=MYSQL COVERAGE_TESTS=18
    - php: 5.6
      env: DB=MYSQL COVERAGE_TESTS=19
    - php: 5.6
      env: DB=MYSQL COVERAGE_TESTS=20
    - php: 5.6
      env: DB=MYSQL COVERAGE_TESTS=21
    - php: 5.6
      env: DB=MYSQL COVERAGE_TESTS=22
    - php: 5.6
      env: DB=MYSQL COVERAGE_TESTS=23
    - php: 5.6
      env: DB=MYSQL COVERAGE_TESTS=24
    - php: 5.6
      env: DB=MYSQL COVERAGE_TESTS=25

before_script:
# Until http://pecl.php.net/package/imagick is working again
# - printf "\n" | pecl install imagick
 - composer self-update || true
 - phpenv rehash
 - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
 - "if [ \"$BEHAT_TEST\" = \"\" ]; then php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss; fi"
 - "if [ \"$BEHAT_TEST\" = \"1\" ]; then php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss --require silverstripe/behat-extension; fi"
 - cd ~/builds/ss
 - php ~/travis-support/travis_setup_selenium.php --if-env BEHAT_TEST
 - php ~/travis-support/travis_setup_php54_webserver.php --if-env BEHAT_TEST

script:
 - "if [ \"$COVERAGE_TESTS\" = \"1\" ]; then vendor/bin/phpunit --coverage-clover=coverage.clover $MODULE_PATH/tests/api; fi"
 - "if [ \"$COVERAGE_TESTS\" = \"2\" ]; then vendor/bin/phpunit --coverage-clover=coverage.clover $MODULE_PATH/tests/control; fi"
 - "if [ \"$COVERAGE_TESTS\" = \"3\" ]; then vendor/bin/phpunit --coverage-clover=coverage.clover $MODULE_PATH/tests/email; fi"
 - "if [ \"$COVERAGE_TESTS\" = \"4\" ]; then vendor/bin/phpunit --coverage-clover=coverage.clover $MODULE_PATH/tests/forms; fi"
 - "if [ \"$COVERAGE_TESTS\" = \"5\" ]; then vendor/bin/phpunit --coverage-clover=coverage.clover $MODULE_PATH/tests/integration; fi"
 - "if [ \"$COVERAGE_TESTS\" = \"6\" ]; then vendor/bin/phpunit --coverage-clover=coverage.clover $MODULE_PATH/tests/model; fi"
 - "if [ \"$COVERAGE_TESTS\" = \"7\" ]; then vendor/bin/phpunit --coverage-clover=coverage.clover $MODULE_PATH/tests/phpcs; fi"
 - "if [ \"$COVERAGE_TESTS\" = \"8\" ]; then vendor/bin/phpunit --coverage-clover=coverage.clover $MODULE_PATH/tests/search; fi"
 - "if [ \"$COVERAGE_TESTS\" = \"9\" ]; then vendor/bin/phpunit --coverage-clover=coverage.clover $MODULE_PATH/tests/templates; fi"
 - "if [ \"$COVERAGE_TESTS\" = \"10\" ]; then vendor/bin/phpunit --coverage-clover=coverage.clover $MODULE_PATH/tests/assets; fi"
 - "if [ \"$COVERAGE_TESTS\" = \"11\" ]; then vendor/bin/phpunit --coverage-clover=coverage.clover $MODULE_PATH/tests/core; fi"
 - "if [ \"$COVERAGE_TESTS\" = \"12\" ]; then vendor/bin/phpunit --coverage-clover=coverage.clover $MODULE_PATH/tests/i18n; fi"
 - "if [ \"$COVERAGE_TESTS\" = \"13\" ]; then vendor/bin/phpunit --coverage-clover=coverage.clover $MODULE_PATH/tests/javascript; fi"
 - "if [ \"$COVERAGE_TESTS\" = \"14\" ]; then vendor/bin/phpunit --coverage-clover=coverage.clover $MODULE_PATH/tests/oembed; fi"
 - "if [ \"$COVERAGE_TESTS\" = \"15\" ]; then vendor/bin/phpunit --coverage-clover=coverage.clover $MODULE_PATH/tests/security; fi"
 - "if [ \"$COVERAGE_TESTS\" = \"16\" ]; then vendor/bin/phpunit --coverage-clover=coverage.clover $MODULE_PATH/tests/testing; fi"
 - "if [ \"$COVERAGE_TESTS\" = \"17\" ]; then vendor/bin/phpunit --coverage-clover=coverage.clover $MODULE_PATH/tests/cache; fi"
 - "if [ \"$COVERAGE_TESTS\" = \"18\" ]; then vendor/bin/phpunit --coverage-clover=coverage.clover $MODULE_PATH/tests/dev; fi"
 - "if [ \"$COVERAGE_TESTS\" = \"19\" ]; then vendor/bin/phpunit --coverage-clover=coverage.clover $MODULE_PATH/tests/filesystem; fi"
 - "if [ \"$COVERAGE_TESTS\" = \"20\" ]; then vendor/bin/phpunit --coverage-clover=coverage.clover $MODULE_PATH/tests/injector; fi"
 - "if [ \"$COVERAGE_TESTS\" = \"21\" ]; then vendor/bin/phpunit --coverage-clover=coverage.clover $MODULE_PATH/tests/parsers; fi"
 - "if [ \"$COVERAGE_TESTS\" = \"22\" ]; then vendor/bin/phpunit --coverage-clover=coverage.clover $MODULE_PATH/tests/tasks; fi"
 - "if [ \"$COVERAGE_TESTS\" = \"23\" ]; then vendor/bin/phpunit --coverage-clover=coverage.clover $MODULE_PATH/tests/view; fi"
 - "if [ \"$COVERAGE_TESTS\" = \"24\" ]; then vendor/bin/phpunit --coverage-clover=coverage.clover $MODULE_PATH/admin/tests; fi"
 - "if [ \"$COVERAGE_TESTS\" = \"25\" ]; then vendor/bin/phpunit --coverage-clover=coverage.clover $MODULE_PATH/tests/*Test.php; fi"


after_failure:
 - php ~/travis-support/travis_upload_artifacts.php --if-env BEHAT_TEST,ARTIFACTS_AWS_SECRET_ACCESS_KEY --target-path $TRAVIS_REPO_SLUG/$TRAVIS_BUILD_ID/$TRAVIS_JOB_ID --artifacts-base-url https://s3.amazonaws.com/$ARTIFACTS_S3_BUCKET/
  - mv coverage.clover ~/build/$TRAVIS_REPO_SLUG/
  - cd ~/build/$TRAVIS_REPO_SLUG
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
  - codecov

branches:
  except:
    - 2.1
    - 2.2
    - 2.3
    - translation-staging

# Generate code coverage
after_script:
  - mv coverage.clover ~/build/$TRAVIS_REPO_SLUG/
  - cd ~/build/$TRAVIS_REPO_SLUG
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
  - codecov

#  global:
#   - secure: "AZmjVPtUD8JBA7ag4ULlEwEKXSEZbIUjDHeRBFugaOtdsn5yigGLmwYbzsg2tq7k7UkdbbAlGct0SUbiRJb9F2wPA5+eUd/p49fgDIU6CTSWIlT87H2BwgOrxKwS9sDwxLptPFM6vWQ8JKYSNGmVIepie9kQZbu4L2k5k6B69jQ="
#   - secure: "f3kKpUn9cS5K+p/E52cMqN18cDApol/43LanDmHO6mo3iRAztk3jZLyfNOUq6JASKMqdh8+9kencRpEoaAYbcQnDPoZsT9POResiJ9/ADKB6RwWy+lcFHUp9E2Zf/x2VRh9FmXEguDhpWzkJqzWYJGCSig1IBp/+TjzKnsjQHIY="
#
# - php ~/travis-support/travis_setup_sauceconnect.php --if-env BEHAT_TEST --username ${SAUCE_USERNAME} --access-key ${SAUCE_ACCESS_KEY} --tunnel-identifier ${TRAVIS_JOB_NUMBER} --base-url http://localhost
